name: Wompi API Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  checks: write
  contents: read

jobs:
  test:
    name: Run Wompi API Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Download dependencies
      run: mvn dependency:resolve
        
    - name: Verify Java and Maven setup
      run: |
        java -version
        mvn -version
        echo "Current directory: $(pwd)"
        ls -la
        echo "Checking test resources:"
        ls -la src/test/resources/
        echo "Checking config file:"
        cat src/test/resources/config.properties
        
    - name: Test API connectivity
      run: |
        echo "Testing connectivity to Wompi API..."
        curl -I https://api.co.uat.wompi.dev/v1/merchants/ || echo "API not accessible"
        
    - name: Run tests with Maven
      run: mvn clean test
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          target/cucumber-reports/
          target/surefire-reports/
        retention-days: 30
        
    - name: Upload Cucumber HTML Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cucumber-html-report
        path: target/cucumber-reports/report.html
        retention-days: 30
        
        
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run OWASP Dependency Check (Maven)
        run: mvn org.owasp:dependency-check-maven:check -Dformat=HTML -DoutputDirectory=dependency-check-report

      - name: Upload Security Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-report
          path: dependency-check-report/
          retention-days: 30
        
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Run SpotBugs
      run: |
        mvn spotbugs:check
      continue-on-error: true